[package]
name = "azero-tools-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = "0.31"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }

async-trait = "0.1.73"
assert_matches = "1.5.0"
base58 = { version = "0.2.0" }
bitvec = { version = "1", default-features = false }
blake2 = { version = "0.10.4", default-features = false }
clap = { version = "4.4.6", features = ["derive", "cargo"] }
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
color-eyre = "0.6.1"
console_error_panic_hook = "0.1.7"
darling = "0.20.3"
derivative = "2.2.0"
either = "1.9.0"
frame-metadata = { version = "16.0.0", default-features = false, features = ["current", "std"] }
futures = { version = "0.3.27", default-features = false, features = ["std"] }
getrandom = { version = "0.2", default-features = false }
hex = "0.4.3"
heck = "0.4.1"
impl-serde = { version = "0.4.0" }
jsonrpsee = { version = "0.20" }
pretty_assertions = "1.4.0"
primitive-types = { version = "0.12.1", default-features = false, features = ["codec", "scale-info", "serde"] }
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.67"
quote = "1.0.33"
regex = "1.9.6"
scale-info = "2.9.0"
scale-value = "0.12.0"
scale-bits = "0.4.0"
scale-decode = "0.9.0"
scale-encode = "0.5.0"
serde = { version = "1.0.188" }
serde_json = { version = "1.0.107" }
syn = { version = "2.0.15", features = ["full", "extra-traits"] }
thiserror = "1.0.48"
tracing = "0.1.34"
tracing-wasm = "0.2.1"
tracing-subscriber = "0.3.17"
trybuild = "1.0.85"
wabt = "0.10.0"
wasm-bindgen-test = "0.3.24"
which = "4.4.2"
